// <auto-generated />
using EpicodusPets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Pets.Migrations
{
    [DbContext(typeof(PetsContext))]
    [Migration("20191028172843_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EpicodusPets.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Description");

                    b.Property<string>("FavoriteThings");

                    b.Property<string>("Gender");

                    b.Property<string>("LeastFavoriteThings");

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.Property<string>("Species");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = 6,
                            Description = "Grey, lanky, fluffy, distinct underbite",
                            FavoriteThings = "Chicken, tortellini, beach, snow, being cozy",
                            Gender = "Female",
                            LeastFavoriteThings = "Grooming, vet visits, guitars, being alone",
                            Name = "Sylvie",
                            Owner = "Jacqueline",
                            Species = "Shih-tzu mix"
                        },
                        new
                        {
                            PetId = 2,
                            Age = 7,
                            Description = "lazy bum",
                            FavoriteThings = "yogurt, cheese, carrots, sleep",
                            Gender = "Female",
                            LeastFavoriteThings = "Grooming, vet visits, raspberries (not the food), being alone",
                            Name = "Bridget",
                            Owner = "Jason",
                            Species = "Shih-tzu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
