// <auto-generated />
using EpicodusPets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Pets.Migrations
{
    [DbContext(typeof(PetsContext))]
    [Migration("20191029174334_SeedDataPhotos")]
    partial class SeedDataPhotos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EpicodusPets.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Description");

                    b.Property<string>("FavoriteThings");

                    b.Property<string>("Gender");

                    b.Property<string>("LeastFavoriteThings");

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Species");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = 6,
                            Breed = "Shih-tzu mix",
                            Description = "Grey, lanky, fluffy, distinct underbite",
                            FavoriteThings = "Chicken, tortellini, beach, snow, her toys, being cozy",
                            Gender = "Female",
                            LeastFavoriteThings = "Grooming, vet visits, guitars, being cold, being alone",
                            Name = "Sylvie",
                            Owner = "Jacqueline",
                            PhotoPath = "wwwroot/uploads/sylvie-jacqueline.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            Age = 7,
                            Breed = "Shih-tzu",
                            Description = "lazy bum",
                            FavoriteThings = "yogurt, cheese, carrots, sleep",
                            Gender = "Female",
                            LeastFavoriteThings = "Grooming, vet visits, raspberries (not the food), being alone",
                            Name = "Bridget",
                            Owner = "Jason",
                            PhotoPath = "wwwroot/uploads/bridget-jason.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 3,
                            Age = 5,
                            Breed = "Long-hair Domestic Feline",
                            Description = "Floofy McCuddlebug, Diva",
                            FavoriteThings = "naps, snacks, being the little spoon, screaming",
                            Gender = "Male",
                            LeastFavoriteThings = "Toe touches, Watching his brother get affection, Being hungry ",
                            Name = "Chunk",
                            Owner = "Sofia",
                            PhotoPath = "wwwroot/uploads/chunk-sofia.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 4,
                            Age = 7,
                            Breed = "Medium-hair Domestic Feline",
                            Description = "Lovebug, Angel, Shy",
                            FavoriteThings = "Snuggles, Gravy, Treats, Feather",
                            Gender = "Male",
                            LeastFavoriteThings = "Loud noises, Strangers, Sudden movements, Vacuum",
                            Name = "Toad",
                            Owner = "Sofia",
                            PhotoPath = "wwwroot/uploads/toad-sofia.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 5,
                            Age = 6,
                            Breed = "Short-hair Domestic Feline",
                            Description = "A fine boi looking for his furrever girl.",
                            FavoriteThings = "His blanket, chirping at birds and squirrels, snuggling on your lap, licking his butt",
                            Gender = "Male",
                            LeastFavoriteThings = "The vacuum, being picked up, having his nails clipped",
                            Name = "Winston",
                            Owner = "Mike",
                            PhotoPath = "wwwroot/uploads/winston-mike.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 6,
                            Age = 5,
                            Breed = "German Shepard 1st Generation German-American",
                            Description = "A Scooby Doo kinda guy looking for his Nova.",
                            FavoriteThings = "Itch, eat all the human food scraps, long walks in the neighborhood, tennis balls",
                            Gender = "Male",
                            LeastFavoriteThings = "Boxes, rain, baths, anything outdoors (except snow)",
                            Name = "Roscoe",
                            Owner = "Jen",
                            PhotoPath = "wwwroot/uploads/roscoe-jen.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 7,
                            Age = 1,
                            Breed = "Medium-hair Domestic Feline",
                            Description = "Mau is friendly to a fault.",
                            FavoriteThings = "Mau enjoys taking naps and climbing house plants.",
                            Gender = "Female",
                            LeastFavoriteThings = "Rain and being told what to do",
                            Name = "Mau",
                            Owner = "Micah",
                            PhotoPath = "wwwroot/uploads/mau-micah.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 8,
                            Age = 12,
                            Breed = "Dutch Shepherd",
                            Description = "A scary looking dog that is a true sweetheart",
                            FavoriteThings = "Jasper loves stuffed toys, food, cheese, and water",
                            Gender = "Male",
                            LeastFavoriteThings = "Rain. Loud Noises.",
                            Name = "Jasper",
                            Owner = "Erin(Chris's wife)",
                            PhotoPath = "wwwroot/uploads/jasper-chris.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 9,
                            Age = 4,
                            Breed = "Australian Cattledog",
                            Description = "Wren is a red heeler that loves to pick on other dogs",
                            FavoriteThings = "Wren loves chasing her favorite toy at the park, she loves belly rubs, and cheese.",
                            Gender = "Female",
                            LeastFavoriteThings = "Rain and being told what to do",
                            Name = "Wren",
                            Owner = "Chris",
                            PhotoPath = "wwwroot/uploads/wren-chris.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 10,
                            Age = 2,
                            Breed = "Australian Shepherd",
                            Description = "Ridiculously fluffy and adorable, and knows it",
                            FavoriteThings = "All squeeky toys.",
                            Gender = "Female",
                            LeastFavoriteThings = "Limes",
                            Name = "Molly",
                            Owner = "Christine",
                            PhotoPath = "wwwroot/uploads/molly-christine.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 11,
                            Age = 3,
                            Breed = "Ball Python",
                            Description = "Very Curious, loves to get into trouble spots.",
                            FavoriteThings = "Climbing Branches.",
                            Gender = "Female",
                            LeastFavoriteThings = "Fast Movement",
                            Name = "Uwa",
                            Owner = "Erin",
                            PhotoPath = "wwwroot/uploads/uwa-erin.jpg",
                            Species = "Snake"
                        },
                        new
                        {
                            PetId = 12,
                            Age = 4,
                            Breed = "Russian Blue Mix",
                            Description = "Fluffy, talkative, will steal your cheese.",
                            FavoriteThings = "Pets and butt scratches",
                            Gender = "Female",
                            LeastFavoriteThings = "Thunder and Vacuums",
                            Name = "Mocha",
                            Owner = "Erin",
                            PhotoPath = "wwwroot/uploads/mocha-erin.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 13,
                            Age = 1,
                            Breed = "Unknown",
                            Description = "Dangerous",
                            FavoriteThings = "Total domination, sleeping",
                            Gender = "Male",
                            LeastFavoriteThings = "Being locked up",
                            Name = "Stripes",
                            Owner = "Carrie",
                            PhotoPath = "wwwroot/uploads/stripes-carrie.jpg",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 14,
                            Age = 3,
                            Breed = "Coonhound/Lab",
                            Description = "The best dog ever",
                            FavoriteThings = "hikes",
                            Gender = "Female",
                            LeastFavoriteThings = "shower",
                            Name = "Kima",
                            Owner = "Joel",
                            PhotoPath = "wwwroot/uploads/kima-joel.jpg",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 15,
                            Age = 6,
                            Breed = "Domestic short hair",
                            Description = "Has an adorable moustache",
                            FavoriteThings = "sleeping",
                            Gender = "Male",
                            LeastFavoriteThings = "screaming toddlers",
                            Name = "Ashford",
                            Owner = "Anita",
                            PhotoPath = "wwwroot/uploads/ashford-anita.jpg",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
